### PR TITLE
Added support for Message Streams

### PR DESCRIPTION
**Pull request by matt-west**
### Description
This PR introduces a new setting to specify the ID of the [Postmark Message Stream](https://postmarkapp.com/support/article/1207-how-to-create-and-send-through-message-streams) that should be used to send messages from Craft. If no ID is set, Postmark will fallback to using the default transactional Message Stream.

The MessageStream ID is passed to the transport class using the `X-PM-Message-Stream` header.

I’ve updated the README and CHANGELOG to reflect these changes.

Screenshot 2020-12-17 at 16 37 05

### Related issues

This is related to #11 but doesn’t explicitly solve the issue of sending through multiple Message Streams. (I’m not familiar with the [Campaign](https://putyourlightson.com/plugins/campaign) plugin.)

### CODE REVIEW

**Comment by leightonhughes** [comment]
Hi @matt-west, keen to have 2.0.3 merged in. Would you be able to follow up?

**Comment by matt-west** [comment]
This is awaiting a code review.

@angrybrad Let me know if you'd like any changes to this.

**Comment by angrybrad** [comment]
@matt-west The PR looks good - tested and it works. Out of curiosity, is there any benefit or downside of using a broadcast stream over a transactional steam? Craft can only be configured to use one mailer, so if someone enters a message ID that happens to be a broadcast stream, _all_ of Craft's emails (password resets, account activation, etc.) will end up going through it.

**Comment by matt-west** [comment]
@angrybrad Thanks Brad. It's okay to send transactional messages through a broadcast stream.

We ask customers to split their sending for a few reasons, but mainly because we handle transactional and broadcast sends a bit differently. For example, we may need to throttle or slow down high-volume broadcast sends to ensure the messages don't get rejected by receivers. There's a chance that transactional messages could be delayed slightly if they get caught up in a big broadcast send, but they'll still get delivered.

**Comment by brandonkelly** [comment]
Just released v2.1.0 with this new setting. Thanks for the PR, @matt-west!

**Pull request merged**
